Feat/#9 mainhome view
NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-Android pull request #15
Opened 2024-05-18 05:12 UTC by leeseokchan00

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #9 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- mainhome page view
- navigate to 사전예약
- sticky header
- top, bottom banner
- 이달의 행사

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-Android/assets/112953135/24928d12-f440-457a-9a8f-c88f551b200e

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
사전예약 화면대응, 이달의 행사 오른쪽 배너 고쳐야합니다. 할 줄 아는 사람...

2024-05-18 22:05 UTC, chanubc requested changes
리뷰 확인해주세요!!
많은 내용인데 고생많으셨습니다

하단의 좌측 뷰페이저는 지워주세요! 이미지 뷰로 하는게 더 나을 것 같습니다

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeBannerAdapter.kt
> +
불필요한 공백 제거 해주세요!

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeBannerViewHolder.kt
> +        binding.ivMainTopBannerImage.setImageResource(data.image)
추후에 서버 통신시에는 coil 라이브러리로 바꾸시면 됩니다!

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
>  }
```suggestion
    override fun onDestroyView() {
        super.onDestroyView()
        autoScrollJob?.cancel() // 예시 네이밍
        _reqresAdapter = null  // 예시 네이밍
    }
}
```

job과 어뎁터는 onDestoryView시에 null처리 해주세요! 메모리 누수의 위험이 있습니다

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +    private var adapter: HomeMonthEventAdapter? = null
adpater하면 어떠한 목적인지 알기가 어렵습니다! 네이밍 수정해주세요
```kotlin
  private var _reqresAdapter: ReqresAdapter? = null
  private val reqresAdapter: ReqresAdapter
        get() = requireNotNull(_reqresAdapter)
```
추가로 값 할당 혹은 초기화시에는 backing property이용하는 것이 좀 더 안전합니다!

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +    var monthEventJob2: Job? = null
job 1,2 는 어떠한 목적인지 알기가 어렵습니다. monthEvenntJobRight 이런식으로 바꾸는게 어떨까요?
그리고 Left의 경우는 뷰페이저를 사용할 필요가 없어짐에 따라 없어도 될것 같습니다!

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +                delay(2000)
2초 너무 길지 않아요?ㅋㅋㅋ
1초나 1.5초 어때요 어차피 보여주기 용이라

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +        adapter?.submitList(eventList)
이미 초기화를 한 상태에서 adapter에 null이 붙는 경우가 있나요?

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +        adapter?.submitList(eventList)
```kotlin
 private fun initRecyclerView() {
        _homeMonthEventAdapter = HomeMonthEventAdapter().apply { // 이 어뎁터가 전역으로 만들어졌다는 가정하에
            submitList(homeViewModel.eventList)
        }
        binding.vpMainMonthEvent2.adapter = homeMonthEventAdapter

        val homeSnapHelper = LinearSnapHelper().apply {
            attachToRecyclerView(binding.vpMainMonthEvent2)
        }

        onScrollStateChanged(homeSnapHelper, homeMonthEventAdapter)
    }

    private fun onScrollStateChanged(
        homeSnapHelper: LinearSnapHelper,
        homeMonthEventAdapter: HomeMonthEventAdapter,
    ) {
        binding.vpMainMonthEvent2.addOnScrollListener(object : RecyclerView.OnScrollListener() {
            override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
                super.onScrollStateChanged(recyclerView, newState)
                if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                    val layoutManager = recyclerView.layoutManager as LinearLayoutManager
                    val centerView = homeSnapHelper.findSnapView(layoutManager)
                    centerView?.run {
                        val pos = layoutManager.getPosition(this)
                        val item = homeMonthEventAdapter.currentList.getOrNull(pos)
                        Log.d("RecyclerView", "현재 포지션: $pos, 아이템: $item")
                        homeViewModel.updateImageResource(pos)
                    }
                }
            }
        })
    }


private fun observeSelectedImage() { //initView()블록안에서 부르면 됨
        homeViewModel.selectedImageResource.observe(viewLifecycleOwner) {
            binding.vpMainMonthEvent1.setImageResource(homeViewModel.eventList[it - 1].image)
        }
}

```

```kotlin
class HomeViewModel : ViewModel() {
    private val _selectedImageResource = MutableLiveData<Int>()
    val selectedImageResource: LiveData<Int> get() = _selectedImageResource

    fun updateImageResource(resource: Int) {
        _selectedImageResource.value = resource
    }

    val eventList: List<HomeBanner> = listOf(
        HomeBanner(R.drawable.img_main_month_event1),
        HomeBanner(R.drawable.img_main_month_event2),
        HomeBanner(R.drawable.img_main_month_event3),
        HomeBanner(R.drawable.img_main_month_event1),
        HomeBanner(R.drawable.img_main_month_event2),
        HomeBanner(R.drawable.img_main_month_event3),
    )
}
```
<br><br>

어차피 데이터는 서버에서 받아올거고 뷰모델있을테니 뷰모델로 더미 리스트를 옮겨서 진행했습니다!
1.좌측 뷰페이저를 이미지뷰로 바꿈
2. 우측 어뎁터가 움직이고 최종 멈출때 해당 포지션 값을 가져옴
```kotlin
   override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
                super.onScrollStateChanged(recyclerView, newState)
                if (newState == RecyclerView.SCROLL_STATE_IDLE) {
```
3. 해당 포지션 값을 뷰모델의 라이브데이터에 set
4. 라이브데이터를 observe해서 이미지에 뷰바인딩

하는 방식입니다!

추가로 liveData말고 staeFlow를 사용해도 무방합니다! 전 staeFlow사용을 좀더 선호하는 편입니다. -> 플랫폼에 종속적이지 않음. 비동기 처리가 불가하기 때문에 메인스레드에서 객체 관찰이 이루어짐(사실 지금 코드에선 상관없음. data layer로 가는 경우는 문제가 발생)
https://onlyfor-me-blog.tistory.com/557
아마 다음주에 배울건데 차이를 알아보는 것도 좋겠습니다!

또한 scope함수 등을 통해서 코드 정리 할수 있겠지만 진행하진 않았습니다

2024-05-18 22:05 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeMonthEventAdapter.kt
> +
불필요한 공백도 지워주세요!

2024-05-18 22:05 UTC, chanubc commented on app/src/main/res/layout/fragment_home.xml
```kotlin
android:background="@color/grey_02"
```

2024-05-18 22:05 UTC, chanubc commented on app/src/main/res/layout/item_main_month_event.xml
> +        android:adjustViewBounds="true"
```suggestion
        android:scaleType="centerCrop"
```
서버 통신해봤는데 기기 대응 안되면 이걸로 바꾸시고 크기는 고정dp넣은 다음에 dimiesnration를 1로 주시면 됩니다!
서버에서 내려주는 이미지 크기가 다를 수가있어서 리사이클러뷰같은 경우는 고정 dp 넣는게 더 나을 수도 있어요!

이건 통신해보고 말씀해주세요

2024-05-18 22:06 UTC, chanubc commented on app/src/main/res/layout/item_main_banner.xml
> +        android:id="@+id/iv_main_top_banner_image"
```suggestion
        android:id="@+id/iv_home_top_banner_image"
```

2024-05-18 22:17 UTC, chanubc commented on app/src/main/res/layout/fragment_home.xml
> +    <androidx.coordinatorlayout.widget.CoordinatorLayout
```kotlin
android:background="@color/grey_02"
```

2024-05-20 16:03 UTC, hyeumm approved these changes
찬우 오빠가 꼼꼼하게 잘 달아줘서 저는 할 말이 없군요... 홈 화면 되게 어려워보이던데.. 역시 천재만재!!

2024-05-20 16:03 UTC, hyeeum commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +                if (bottomBannerCurrentPosition == 3) {
리스트 사이즈 를 가져와도 괜찮을 것 같아요..!

2024-05-22 12:54 UTC, chanubc approved these changes

2024-05-22 12:55 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +    var monthEventJob2: Job? = null
p1

2024-05-22 12:55 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
> +        adapter?.submitList(eventList)
p1인데 안되면 일단 머지하고 체크해 봅시다!

2024-05-22 12:55 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/home/HomeFragment.kt
>  }
p1

2024-05-22 13:38 UTC, merged