Feat/#12 reservation
NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-Android pull request #18
Opened 2024-05-19 18:29 UTC by hyeumm

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #12 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- collapsing toolbar
- tablayout
- viewpager
- grid view
- recyclerview
- floating action bar

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-Android/assets/118244028/5693e31d-9aea-4efe-b3b4-bf162005e021

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
collapsing toolbar <- 툴바 축소 시 아이콘을 띄우는 부분에서 막혔습니다.. 최종 ui 기한이 지나서 일단은 PR 올립니당..
하다보니까 수정할게 이만저만이 아닌 것 같아 PR이 늦었습니다 ㅠ
제가 코드 짜는게 굉장히 느리다는 걸 체감할 수 있는 일주일이었습니다... 부족한 실력이지만 수정사항 열심히 반영겠습니다!!!

2024-05-20 05:21 UTC, leeseokchan00 commented
고생하셨습니다👍👍 코틀린 파일들은 폴더링 한번 하는게 좋을 것 같아요.

2024-05-21 19:23 UTC, chanubc requested changes
엄청난 양인데 잘하셨네요 ㄷㄷ
전체적으로 data class는 마지막 끝을 page 대신 entity로 수정해주세요!
또 entity class 들은 따로 feature-util 디렉토리를 만들어서
한번에 관리해주세요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveBannerAdapter.kt
> +class ViewPagerAdapter(private val listData: ArrayList<ReserveBannerPage>) : RecyclerView.Adapter<ReservePageViewHolder>() {
```suggestion
class ViewPagerAdapter(private val listData: ArrayList<ReserveBannerEntity>) : RecyclerView.Adapter<ReservePageViewHolder>() {
```
data class는 끝이 Data 혹은  Entity로 끝나는게 좋습니다!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveBannerAdapter.kt
> +
R을 사용하지 않고 다른 어뎁터와 같이 binding을 사용해주세요! 아래에는 잘 되있네용

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveBannerAdapter.kt
> +    override fun getItemCount(): Int = Int.MAX_VALUE
효과적인 무한 스크롤이긴하나 다른 방법이 있는지 찾아볼게요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveDiscountAdapter.kt
> +class ReserveDiscountAdapter() : RecyclerView.Adapter<ReserveDiscountViewHolder>() {
ListAdapter사용해 보는건 어떤가요?
util 에 itemDiffCallBack클래스를 정의해 놓았습니다! 사용방법은 따로 설명 드릴게요

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveBannerPage.kt
> +data class ReserveBannerPage(var image: Int, var title: String)
p1 : 
```suggestion
data class ReserveBannerEntity(val image: Int, val title: String)
```

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveDiscountMenu.kt
> +data class ReserveDiscountMenu (
p1 : 요것도 data class니까 뒤에 Entity를 붙여줍시다!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveDiscountViewHolder.kt
> +            tvReserveDiscountMenuOriginalPrice.paintFlags =
좋아요!!!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveDiscountViewHolder.kt
> +            tvReserveDiscountMenuPrice.text = itemView.context.getString(R.string.reserve_menu_price, discountMenuData.price)
오 string format 좋네요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveMenuCategory2Adapter.kt
> +            context.getString(R.string.reserve_menu_review, currentItem.menuCategoryReview)
p1 : R 대신 binding을 사용해주세요! - feat : 1차세미나

### `findViewById()`를 쓰지 않는 이유

1. 이 함수를 깊게 들어가보시면 알 수 있습니다. 이 함수가 뷰 객체들을 찾는 방식은 자식 뷰들을 하나하나 탐색하여 id가 같은 뷰가 있으면 반환하고 종료하도록 로직이 구성되어 있습니다. **깊이우탐색(DFS)**과 동일하기에 시간이 오래 걸리겠죠? **탐색 비용이 높다**고 볼 수 있습니다.

1. **타입 캐스팅** : 가져온 뷰 객체를 특정 뷰(TextView, Button 등)으로 사용하면 해당 타입으로 캐스팅 해야 합니다. 번거롭죠?

1. **Null Safety** : 항상 개발자는 Null 안정성에 대해 고민하고 이에 대비해야 합니다. 이 매서드를 통해 얻은 ID의 뷰가 존재하지 않을 경우? Null을 반환합니다. 그럼 **NullPointerException** 대한 대비를 해주어야겠죠? 

1. **안정성**: `findViewById` 는 런타임에 반영되지만, View Binding은 런타임에 반영이 아닌 컴파일 타임에 안전하고, 타입 안정성을 제공합니다.

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveMenuCategory2Adapter.kt
> +    BaseAdapter() {
이건 처음보네요 ㄷㄷ

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveMenuListAdapter.kt
> +//    }
p1 : 불필요한 주석은 지워주세요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/item_reserve_category2.xml
> +        android:layout_height="20dp"
p1 : 텍스트 뷰는 wrap content혹은 0dp 활용해주세요!
또 xml 네이밍에서 1,2는 허용하지 않겠습니다..! 위치에 따라 top bottom 혹은 left right로 정합시다~

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/item_reserve_category.xml
> +        android:layout_height="20dp"
p1:  text의 경우 반드시 wrap이나 0dp 사용해주세요!! 화면 크기에따라 sp는 텍스트 크기가 바뀌는데 이러면 기기에 따라 잘릴 가능성이 높습니다!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/values/strings.xml
> +    <string name="reserve_menu_review">후기%1$d</string>
주석도 gooood!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/fragment_reserve.xml
> +                        android:text="우리집"
p2 : 요런 고정 text는 string 추출 해주세요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/drawable/shape_grey00_fill_circle.xml
> +    <size android:width="34dp" android:height="34dp"/>
p3: size는 필요없습니다! background로 주면 해당 뷰의 크기만큼 적용 되요

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/drawable/shape_grey00_fill_circle.xml
> +    <size android:width="34dp" android:height="34dp"/>
저는 이런 shpae들에는 크기지정은 안하고 shape를 사용하는 view에서 크기 지정을 하는 편입니다!
이래야 여러 군데에서 사용 가능하거든요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/fragment_reserve.xml
> +                    app:shapeAppearance="@drawable/shape_grey00_line_circle" />
이 방법도 간단하고 좋네요!!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/item_reserve_top_banner.xml
> +            android:id="@+id/iv_reserve_banner"
p1 : scayleType = "center"
적용해주세요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/item_reserve_top_banner.xml
> +            android:layout_width="wrap_content"
top banner라 폭은 wrap이 아니라 match parent가 되어야 하지 않을까요??
서버에서 불러오는 이미지가 작아서 wrap으로 하면 작게 나오지 않을까 싶습니다

2024-05-21 19:23 UTC, chanubc commented on app/src/main/res/layout/item_reserve_top_banner.xml
> +            android:layout_width="wrap_content"
p1 : 이런 배너같이 큰 이미지의 폭, 높이 의 경우 저번에 말씀 드렸던 것 처럼 0dp 0dp 선언하고
비율을 주면 됩니다!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +        }
p1 : 아마 지워질 코드이지만 let을 null체크 용으로 사용한다면 run을 사용하는게 더 낫습니다! 또 scopㄷ가 중복될 필요도 없어보여요!
```suggestion
       bannerItems?.run {
                 add(ReserveBannerPage(R.drawable.img_reserve_banner1, "1"))
                 add(ReserveBannerPage(R.drawable.img_reserve_banner2, "2"))
        }

```

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +    private var bannerPosition = 0
p1 : 
```suggestion
    private lateinit var bannerJob: Job
    private var bannerPosition = 0
```

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +        moveToTop()
p3 : 함수는 호출 순서에 따라 작성하는 것이 가독성에 좋습니다!
setBannerItems() 함수가 첫번째라면 initView 블록 밖에서는 setBannerItems가 제일 먼저 배치 되어야 되겠죠?

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +        initMenuCategory2Adapter()
p1 : 저는 컨밴션을 절대 강제하는 스타일은 아니지만...
네이밍을 1,2로 지어서는 안됩니다!! 다른 개발자들이 어떠한 것인지 파악하기 힘들어요
위치로 구분한다면 차라리 top bottom 혹은 left right으로 하는게 나을 것 같아요!

2024-05-21 19:23 UTC, chanubc commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +    }
job해제 좋습니다!

2024-05-21 19:56 UTC, hyeumm commented on app/src/main/res/drawable/shape_grey00_fill_circle.xml
> +    <size android:width="34dp" android:height="34dp"/>
앗 정말로 생각해보니 재사용하려면 이렇게 크기를 지정하면 안되는군요 당연한건데 미처 생각못한부분이네요...!!!

2024-05-21 19:57 UTC, hyeumm commented on app/src/main/java/com/sopt/now/gs/feature/reserve/ReserveFragment.kt
> +        initMenuCategory2Adapter()
이 부분 네이밍 어떻게 해야할지 고민많았는데 짚어주셔서 감사합니닷..!!!!

2024-05-22 06:41 UTC, hyeumm commented on app/src/main/res/layout/item_reserve_top_banner.xml
> +            android:layout_width="wrap_content"
비율의 경우 item xml의 이미지뷰와 fragment xml의 뷰페이저 둘 다 적용해줘야하나요 아니면 뷰페이저만 적용해도 괜찮나요???

2024-05-22 14:04 UTC, chanubc commented on app/src/main/res/layout/item_reserve_top_banner.xml
> +            android:layout_width="wrap_content"
뷰페이저만 적용해도 괜찮습니다!
리사이클러뷰의 item이미들을 wrap content하게 되면 어차피 서버에서 내려오는 이미지 크기 만큼 되기때문에
사실상 고정dp로 고정하나 똑같습니다! 서버에서 고정 dp를 주는 거죠

하지만 뷰페이저 같이 커다란 배너의 경우 우리쪽에서 일정한 비율의 크기를 가져 가야 하기 때문에 비율을 지정해 주는 것이 좋습니다!

물론 리사이클러뷰도 비율 조정을 하면 좋겠지만 리사이클러뷰의 경우 결국 height에 wrap을 해야 하거나 높이를 고정 dp로 주어야 하는데 이러면 이미지에 고정 dp를 주는것과 동일한 작업이 됩니다!

2024-05-22 14:31 UTC, chanubc approved these changes
고생하셨습니다!!

2024-05-22 14:35 UTC, merged